revChatGPT/Exceptions.py,sha256=70Dmggf9AQGBKnfg0NJJmyKugBUig42THIs6OD5jeMA,632
revChatGPT/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
revChatGPT/__main__.py,sha256=GTra9vziEN5Cd1uMmQjX6A4Q1UwPiRMawcZfD94Do6A,5454
revChatGPT/revChatGPT.py,sha256=0cLVCsc2vh3skv1JC2bv-G7CSpkHdkiBS32k9sPOW8k,20671
revChatGPT-0.0.44.1.dist-info/LICENSE,sha256=gXf5dRMhNSbfLPYYTY_5hsZ1r7UU1OaKQEAQUhuIBkM,18092
revChatGPT-0.0.44.1.dist-info/METADATA,sha256=I42Su5w2t06noifqPrZN2fSpdsQIacTUXXAgpfrODWs,3226
revChatGPT-0.0.44.1.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
revChatGPT-0.0.44.1.dist-info/entry_points.txt,sha256=kN59pODjUjDYjYJq0f1yL2RXrf68OFGDYUMjFXEj-50,57
revChatGPT-0.0.44.1.dist-info/top_level.txt,sha256=6O3ay3adff-Qrq0tGYaEe_XXhvCZ5vGC9AshCmZzRMA,11
revChatGPT-0.0.44.1.dist-info/RECORD,,
